site_name: Learn Computer Vision
site_url: "" #TODO(orphen) Update this.
edit_uri: ""

theme:
  name: material
  palette:
    primary: white

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/iamorphen/learn-computer-vision

repo_url: https://github.com/iamorphen/learn-computer-vision

nav:
  - Introduction: index.md
  - Spatial Domain:
    - Introduction: spatial_domain/introduction.md
    - Basic Techniques: spatial_domain/basic_techniques.md

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences

extra_javascript:
  # For arithmatext, mathjax.
  - scripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
