site_name: Learn Computer Vision
site_url: "" #TODO(orphen) Update this.

theme:
  name: material
  palette:
    primary: white

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/iamorphen/learn-computer-vision

repo_url: https://github.com/iamorphen/learn-computer-vision

nav:
  - Introduction: introduction.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  # For arithmatext, mathjax.
  - scripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
